#!/usr/bin/env bash
# =============================================================================
# bw-import-env.sh — One-time import of .env.local into Bitwarden
# =============================================================================
# Reads your existing .env.local and creates a Bitwarden Secure Note with
# custom fields for each env var. Run this once to seed your vault.
#
# Usage:
#   ./scripts/bw-import-env.sh
#
# Prerequisites:
#   - bw login (already logged in)
#   - Vault unlocked (BW_SESSION set or session file exists)
# =============================================================================

set -euo pipefail

PORTSIE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_LOCAL="${PORTSIE_ROOT}/.env.local"
BW_ITEM_NAME="${BW_ITEM_NAME:-Portsie Dev Env}"
BW_SESSION_FILE="${HOME}/.bw-session"

# --- Load session -------------------------------------------------------------
if [ -z "${BW_SESSION:-}" ] && [ -f "${BW_SESSION_FILE}" ]; then
  export BW_SESSION
  BW_SESSION="$(cat "${BW_SESSION_FILE}")"
fi

if [ -z "${BW_SESSION:-}" ]; then
  echo "✗ Vault is locked. Run 'bw-unlock' first (source scripts/bw-secrets.sh && bw-unlock)"
  exit 1
fi

if [ ! -f "${ENV_LOCAL}" ]; then
  echo "✗ No .env.local found at ${ENV_LOCAL}"
  exit 1
fi

# --- Parse .env.local ---------------------------------------------------------
echo "→ Reading ${ENV_LOCAL}..."

# Build JSON fields array from .env.local
FIELDS_JSON="$(python3 -c "
import re, json, sys

fields = []
with open('${ENV_LOCAL}') as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        match = re.match(r'^([A-Z_][A-Z0-9_]*)=(.*)', line)
        if match:
            key, value = match.group(1), match.group(2)
            # Strip surrounding quotes if present
            if len(value) >= 2 and value[0] == value[-1] and value[0] in ('\"', \"'\"):
                value = value[1:-1]
            field_type = 1  # 0=text, 1=hidden
            fields.append({
                'name': key,
                'value': value,
                'type': field_type
            })

json.dump(fields, sys.stdout)
print()
print(f'Found {len(fields)} variables', file=sys.stderr)
")" 2>&1

FIELD_COUNT="$(echo "${FIELDS_JSON}" | tail -1)"
FIELDS_JSON="$(echo "${FIELDS_JSON}" | head -1)"

echo "  ${FIELD_COUNT}"

# --- Check if item already exists ---------------------------------------------
echo "→ Checking if '${BW_ITEM_NAME}' already exists..."

EXISTING_ID="$(bw list items --search "${BW_ITEM_NAME}" --session "${BW_SESSION}" 2>/dev/null \
  | python3 -c "
import json, sys
items = json.load(sys.stdin)
for item in items:
    if item['name'] == '${BW_ITEM_NAME}':
        print(item['id'], end='')
        sys.exit(0)
" 2>/dev/null)" || true

if [ -n "${EXISTING_ID}" ]; then
  echo ""
  echo "⚠  Item '${BW_ITEM_NAME}' already exists (ID: ${EXISTING_ID})"
  echo "   This will UPDATE the existing item with new field values."
  echo ""
  read -rp "   Continue? [y/N] " confirm
  if [[ ! "${confirm}" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi

  # Update existing item — get current JSON, replace fields
  ITEM_JSON="$(bw get item "${EXISTING_ID}" --session "${BW_SESSION}" 2>/dev/null)"
  UPDATED_JSON="$(echo "${ITEM_JSON}" | python3 -c "
import json, sys
item = json.load(sys.stdin)
fields = json.loads('${FIELDS_JSON}')
item['fields'] = fields
json.dump(item, sys.stdout)
")"

  echo "${UPDATED_JSON}" | bw encode | bw edit item "${EXISTING_ID}" --session "${BW_SESSION}" > /dev/null
  echo "✓ Updated '${BW_ITEM_NAME}' with $(echo "${FIELDS_JSON}" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))") fields"

else
  # Create new Secure Note item
  echo "→ Creating new Secure Note '${BW_ITEM_NAME}'..."

  ITEM_JSON="$(python3 -c "
import json, sys
item = {
    'organizationId': None,
    'collectionIds': None,
    'folderId': None,
    'type': 2,  # Secure Note
    'name': '${BW_ITEM_NAME}',
    'notes': 'Portsie development environment secrets. Generated by scripts/bw-import-env.sh. Regenerate .env.local with: source scripts/bw-secrets.sh && bw-env',
    'secureNote': {'type': 0},
    'fields': json.loads('''${FIELDS_JSON}''')
}
json.dump(item, sys.stdout)
")"

  echo "${ITEM_JSON}" | bw encode | bw create item --session "${BW_SESSION}" > /dev/null
  echo "✓ Created '${BW_ITEM_NAME}' with $(echo "${FIELDS_JSON}" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))") fields"
fi

echo ""
echo "Done! Your secrets are now in Bitwarden."
echo ""
echo "Next steps:"
echo "  1. Verify:  bw-get SUPABASE_URL"
echo "  2. Generate: bw-env  (writes .env.local from vault)"
echo "  3. Optionally delete the old .env.local and rely on bw-env"
