export type ConnectionMethod = "api" | "quiltt" | "upload";
export type InstitutionCategory = "brokerage" | "bank";

/** Tab label and description shown in the setup screen */
export const CONNECTION_METHOD_INFO: Record<
  ConnectionMethod,
  { label: string; description: string }
> = {
  api: {
    label: "Connect via API",
    description: "Direct connection using your developer credentials",
  },
  quiltt: {
    label: "Link Account",
    description:
      "Securely connect through your bank login — no API keys needed",
  },
  upload: {
    label: "Upload Files",
    description: "Upload PDF statements, CSV exports, or other documents",
  },
};

export interface BrokerageInfo {
  id: string;
  name: string;
  shortName: string;
  description: string;
  /** Available connection methods in priority order (first = default tab) */
  connectionMethods: ConnectionMethod[];
  category: InstitutionCategory;
  parentCompany?: string;
  logoPlaceholder: string;
  logoDomain: string;
}

export const BROKERAGES: BrokerageInfo[] = [
  // ── Brokerages ──────────────────────────────────────────────
  {
    id: "schwab",
    name: "Charles Schwab",
    shortName: "Schwab",
    description: "Connect via API, link your account, or upload files",
    connectionMethods: ["api", "quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "CS",
    logoDomain: "schwab.com",
  },
  {
    id: "fidelity",
    name: "Fidelity Investments",
    shortName: "Fidelity",
    description: "Link your account or upload statements",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "FI",
    logoDomain: "fidelity.com",
  },
  {
    id: "vanguard",
    name: "Vanguard",
    shortName: "Vanguard",
    description: "Link your account or upload statements",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "VG",
    logoDomain: "vanguard.com",
  },
  {
    id: "td-ameritrade",
    name: "TD Ameritrade",
    shortName: "TD Ameritrade",
    description: "Now part of Charles Schwab",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    parentCompany: "Charles Schwab",
    logoPlaceholder: "TD",
    logoDomain: "tdameritrade.com",
  },
  {
    id: "etrade",
    name: "E*TRADE",
    shortName: "E*TRADE",
    description: "Connect via API, link your account, or upload files",
    connectionMethods: ["api", "quiltt", "upload"],
    category: "brokerage",
    parentCompany: "Morgan Stanley",
    logoPlaceholder: "ET",
    logoDomain: "etrade.com",
  },
  {
    id: "interactive-brokers",
    name: "Interactive Brokers",
    shortName: "IBKR",
    description: "Connect via API, link your account, or upload files",
    connectionMethods: ["api", "quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "IB",
    logoDomain: "interactivebrokers.com",
  },
  {
    id: "robinhood",
    name: "Robinhood",
    shortName: "Robinhood",
    description: "Link your account or upload statements",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "RH",
    logoDomain: "robinhood.com",
  },
  {
    id: "merrill-edge",
    name: "Merrill Edge",
    shortName: "Merrill",
    description: "Link your account or upload statements",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    parentCompany: "Bank of America",
    logoPlaceholder: "ME",
    logoDomain: "merrilledge.com",
  },
  {
    id: "jpmorgan",
    name: "J.P. Morgan Self-Directed",
    shortName: "J.P. Morgan",
    description: "Link your account or upload statements",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "JP",
    logoDomain: "jpmorgan.com",
  },
  {
    id: "alpaca",
    name: "Alpaca",
    shortName: "Alpaca",
    description: "Connect via API, link your account, or upload files",
    connectionMethods: ["api", "quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "AL",
    logoDomain: "alpaca.markets",
  },
  {
    id: "tastytrade",
    name: "Tastytrade",
    shortName: "Tastytrade",
    description: "Connect via API, link your account, or upload files",
    connectionMethods: ["api", "quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "TT",
    logoDomain: "tastytrade.com",
  },
  {
    id: "tradestation",
    name: "TradeStation",
    shortName: "TradeStation",
    description: "Connect via API, link your account, or upload files",
    connectionMethods: ["api", "quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "TS",
    logoDomain: "tradestation.com",
  },
  {
    id: "webull",
    name: "Webull",
    shortName: "Webull",
    description: "Connect via API, link your account, or upload files",
    connectionMethods: ["api", "quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "WB",
    logoDomain: "webull.com",
  },
  {
    id: "ally-invest",
    name: "Ally Invest",
    shortName: "Ally",
    description: "Link your account or upload statements",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "AI",
    logoDomain: "ally.com",
  },
  {
    id: "other-brokerage",
    name: "Other Brokerage",
    shortName: "Other",
    description: "Search for your brokerage and link via secure connection",
    connectionMethods: ["quiltt", "upload"],
    category: "brokerage",
    logoPlaceholder: "BR",
    logoDomain: "broker.com",
  },

  // ── Banks ───────────────────────────────────────────────────
  {
    id: "chase",
    name: "Chase",
    shortName: "Chase",
    description: "Link your checking, savings, or investment accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    parentCompany: "JPMorgan Chase",
    logoPlaceholder: "CH",
    logoDomain: "chase.com",
  },
  {
    id: "bank-of-america",
    name: "Bank of America",
    shortName: "BofA",
    description: "Link your Bank of America accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "BA",
    logoDomain: "bankofamerica.com",
  },
  {
    id: "wells-fargo",
    name: "Wells Fargo",
    shortName: "Wells Fargo",
    description: "Link your Wells Fargo accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "WF",
    logoDomain: "wellsfargo.com",
  },
  {
    id: "citi",
    name: "Citi",
    shortName: "Citi",
    description: "Link your Citibank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "CI",
    logoDomain: "citi.com",
  },
  {
    id: "capital-one",
    name: "Capital One",
    shortName: "Capital One",
    description: "Link your Capital One accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "CO",
    logoDomain: "capitalone.com",
  },
  {
    id: "us-bank",
    name: "U.S. Bank",
    shortName: "US Bank",
    description: "Link your U.S. Bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "US",
    logoDomain: "usbank.com",
  },
  {
    id: "pnc",
    name: "PNC",
    shortName: "PNC",
    description: "Link your PNC bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "PN",
    logoDomain: "pnc.com",
  },
  {
    id: "td-bank",
    name: "TD Bank",
    shortName: "TD Bank",
    description: "Link your TD Bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "TD",
    logoDomain: "td.com",
  },
  {
    id: "truist",
    name: "Truist",
    shortName: "Truist",
    description: "Link your Truist bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "TR",
    logoDomain: "truist.com",
  },
  {
    id: "schwab-bank",
    name: "Charles Schwab Bank",
    shortName: "Schwab Bank",
    description: "Link your Schwab checking or savings accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    parentCompany: "Charles Schwab",
    logoPlaceholder: "CS",
    logoDomain: "schwab.com",
  },
  {
    id: "usaa",
    name: "USAA",
    shortName: "USAA",
    description: "Link your USAA bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "UA",
    logoDomain: "usaa.com",
  },
  {
    id: "navy-federal",
    name: "Navy Federal Credit Union",
    shortName: "Navy Federal",
    description: "Link your Navy Federal accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "NF",
    logoDomain: "navyfederal.org",
  },
  {
    id: "citizens",
    name: "Citizens Bank",
    shortName: "Citizens",
    description: "Link your Citizens Bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "CB",
    logoDomain: "citizensbank.com",
  },
  {
    id: "fifth-third",
    name: "Fifth Third Bank",
    shortName: "Fifth Third",
    description: "Link your Fifth Third accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "53",
    logoDomain: "53.com",
  },
  {
    id: "regions",
    name: "Regions Bank",
    shortName: "Regions",
    description: "Link your Regions Bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "RG",
    logoDomain: "regions.com",
  },
  {
    id: "huntington",
    name: "Huntington Bank",
    shortName: "Huntington",
    description: "Link your Huntington Bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "HN",
    logoDomain: "huntington.com",
  },
  {
    id: "bmo",
    name: "BMO",
    shortName: "BMO",
    description: "Link your BMO bank accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "BM",
    logoDomain: "bmo.com",
  },
  {
    id: "discover",
    name: "Discover Bank",
    shortName: "Discover",
    description: "Link your Discover savings or checking accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "DI",
    logoDomain: "discover.com",
  },
  {
    id: "sofi",
    name: "SoFi",
    shortName: "SoFi",
    description: "Link your SoFi bank or investment accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "SF",
    logoDomain: "sofi.com",
  },
  {
    id: "marcus",
    name: "Marcus by Goldman Sachs",
    shortName: "Marcus",
    description: "Link your Marcus savings accounts",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    parentCompany: "Goldman Sachs",
    logoPlaceholder: "MG",
    logoDomain: "marcus.com",
  },
  {
    id: "other-bank",
    name: "Other Bank",
    shortName: "Other",
    description: "Search for your bank and link via secure connection",
    connectionMethods: ["quiltt", "upload"],
    category: "bank",
    logoPlaceholder: "BK",
    logoDomain: "bank.com",
  },
];

export function getBrokerageById(id: string): BrokerageInfo | undefined {
  return BROKERAGES.find((b) => b.id === id);
}

export function getBrokerages(): BrokerageInfo[] {
  return BROKERAGES.filter((b) => b.category === "brokerage");
}

export function getBanks(): BrokerageInfo[] {
  return BROKERAGES.filter((b) => b.category === "bank");
}
